GET http://localhost:3000/users

###

PUT http://localhost:3000/cards/625ef51744e2be5929b4a6e4/likes



###

PATCH http://localhost:3000/users/me
Content-type: application/json

{
  "name": "Петр2",
  "about": "уже ктото"
}

###

POST http://localhost:3000/users/
Content-Type: application/json

{
  "name": "aboba"
}