GET http://localhost:3000/users/625c676597f3047639f7e6b8

###

PATCH http://localhost:3000/users/me
Content-type: application/json

{
  "name": "Петр2",
  "about": "уже ктото"
}

###

DELETE http://localhost:3000/cards/625eed12ffa8418c42aea9d6